FROM node:10-alpine

MAINTAINER James Tanner "james.tanner@tanndev.com"

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000
ARG JENKINS_AGENT_HOME=/home/${user}
ENV JENKINS_AGENT_HOME ${JENKINS_AGENT_HOME}
RUN addgroup -g ${gid} ${group} \
    && adduser -d "${JENKINS_AGENT_HOME}" -u "${uid}" -g "${gid}" -m -s /bin/bash "${user}"

RUN apk update
RUN apk add --no-cache docker
RUN apk add --no-cache git
RUN apk add --no-cache openssh

WORKDIR "${JENKINS_AGENT_HOME}"
